repos:
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.2.3
  hooks:
   - id: nbqa-isort
   - id: nbqa-black
   - id: nbqa-flake8
- repo: https://github.com/psf/black
  rev: 22.1.0
  hooks:
    - id: black
