name: discursis
channels:
  - conda-forge
  - defaults
dependencies:
  # Try to install everything via conda where possible,
  #   makes for simpler and quicker installs
  - atap_widgets>=0.2.25
  - python=3.9
  - pandas
  - openpyxl
  # xlsxwriter needed for atap_widgets exports
  - xlsxwriter
  - matplotlib
  - jupytext
  - pre-commit
  - black[jupyter]
  - jupyterlab>=3.0
  - jupyter-server-proxy
  - bokeh
  - jupyter_bokeh
  - pytest
  - nbmake
  - nbqa
  - nbval
  - nbformat
  - spacy
  - textacy
  - spacy-model-en_core_web_sm>=3.1
  - click
  - pip
variables:
  BINDER_EXTERNAL_URL: https://notebooks.gesis.org/
