name: atap
channels:
  - conda-forge
  - defaults
dependencies:
  # Try to install everything via conda where possible,
  #   makes for simpler and quicker installs
  - python=3.9
  - pandas
  - matplotlib
  - jupytext
  - pre-commit
  - black[jupyter]
  - jupyterlab>=3.0
  - bokeh
  - jupyter_bokeh
  - pytest
  - nbmake
  - nbqa
  - nbval
  - nbformat
  - spacy-model-en_core_web_sm>=3.1
  # click 8.1+ is currently incompatible with spacy
  - click==8.0.4
  - pip
  - pip:
      - convokit>=2.5.3
      - jupyter-server-proxy
      - atap_widgets==0.2.3-alpha.0
      #- ldaca@git+https://github.com/Language-Research-Technology/ldaca-py.git
