name: atap
channels:
  - conda-forge
  - defaults
dependencies:
  # Try to install everything via conda where possible,
  #   makes for simpler and quicker installs
  - python=3.9
  - pandas
  - openpyxl
  - matplotlib
  - jupytext
  - pre-commit
  - black[jupyter]
  - jupyterlab>=3.0
  - jupyter-server-proxy
  - bokeh
  - jupyter_bokeh
  - pytest
  - nbmake
  - nbqa
  - nbval
  - nbformat
  - spacy
  - textacy
  - spacy-model-en_core_web_sm>=3.1
  - click
  - pip
  - pip:
     # TODO: install this through conda once it's a bit more
     #   stable
      - atap_widgets>=0.2.23
